networks:
  development:
    name: dev-network

services:
  driveup-dev-server:
    container_name: driveup-dev-server
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server/src:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      driveup-dev-database :
        condition: service_healthy
    networks:
      - development

  driveup-dev-client:
    container_name: driveup-dev-client
    build: 
      context: ./client
      dockerfile: Dockerfile.dev 
    volumes:
      - ./client/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
      VITE_SERVER_HOST: ${SERVER_HOST}
      VITE_CLIENT_HOST: ${CLIENT_HOST}
      VITE_STADIA_MAP_API_KEY: ${STADIA_MAP_API_KEY}
    depends_on:
      - driveup-dev-server
    networks:
      - development

  driveup-dev-database:
    container_name: driveup-dev-database
    image: postgres
    volumes:
      - ./persist/data/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    networks:
      - development

  driveup-dev-visualizer:
    container_name: driveup-dev-visualizer
    image: adminer
    networks:
      - development

  driveup-dev-gateway: 
    container_name: driveup-dev-gateway
    image: nginx
    restart: always
    ports: 
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - development
