networks:
  staging:
    name: staging
    driver: bridge

services:
  driveup-staging-server:
    container_name: driveup-staging-server
    image: yannlahellec1025/driveupstagingserver
    command: sh -c "npm run start"
    volumes:
      - ./server/src:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      driveup-staging-database :
        condition: service_healthy
    networks:
      - staging

  driveup-staging-client:
    container_name: driveup-staging-client
    image: yannlahellec1025/driveupstagingclient
    command: sh -c "npm run start"
    volumes:
      - ./client/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
      VITE_SERVER_HOST: ${SERVER_HOST}
      VITE_CLIENT_HOST: ${CLIENT_HOST}
    depends_on:
      - driveup-staging-server
    networks:
      - staging

  driveup-staging-database:
    container_name: driveup-staging-database
    image: postgres
    volumes:
      - ./persist/staging-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    networks:
      - staging

  driveup-staging-gateway: 
    container_name: driveup-staging-gateway
    image: nginx
    restart: always
    ports: 
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.staging.conf:/etc/nginx/nginx.conf
    depends_on:
      - driveup-staging-server
      - driveup-staging-client
    networks:
      - staging