networks:
  production:
    name: production
    driver: bridge

services:
  driveup-prod-backend:
    container_name: driveup-prod-backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/src:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      driveup-prod-database :
        condition: service_healthy
    networks:
      - production

  driveup-prod-frontend:
    container_name: driveup-prod-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
      VITE_BACKEND_HOST: ${BACKEND_HOST}
      VITE_FRONTEND_HOST: ${FRONTEND_HOST}
    depends_on:
      - driveup-prod-backend
    networks:
      - production

  driveup-prod-database:
    container_name: driveup-prod-database
    image: postgres
    volumes:
      - ./persist/prod-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    networks:
      - production

  driveup-prod-gateway: 
    container_name: driveup-prod-gateway
    image: nginx
    restart: always
    ports: 
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - driveup-prod-backend
      - driveup-prod-frontend
    networks:
      - production