networks:
  production:
    name: production
    driver: bridge

services:
  driveup-prod-server:
    container_name: driveup-prod-server
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server/src:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      driveup-prod-database :
        condition: service_healthy
    networks:
      - production

  driveup-prod-seeder:
    container_name: driveup-prod-seeder
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - ./server/src:/app/src
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      APP_SECRET: ${APP_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      GATEWAY_PORT: ${GATEWAY_PORT}
    depends_on:
      driveup-prod-database :
        condition: service_healthy
    command: sh -c "echo '⏳ Waiting for database...' && sleep 5 && echo '🌱 Starting seed...' && npm run seed && echo '✅ Seed completed!'"
    profiles: ["seed"]
    networks:
      - production

  driveup-prod-client:
    container_name: driveup-prod-client
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    volumes:
      - ./client/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
      VITE_SERVER_HOST: ${SERVER_HOST}
      VITE_CLIENT_HOST: ${CLIENT_HOST}
      VITE_UNSPLASH_ACCESS_KEY: ${VITE_UNSPLASH_ACCESS_KEY}

    depends_on:
      - driveup-prod-server
    networks:
      - production

  driveup-prod-database:
    container_name: driveup-prod-database
    image: postgres
    volumes:
      - ./persist/prod-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
    networks:
      - production

  driveup-prod-gateway: 
    container_name: driveup-prod-gateway
    image: nginx
    restart: always
    ports: 
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - driveup-prod-server
      - driveup-prod-client
    networks:
      - production