events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://driveup-prod-frontend:5173;
        }

        location /api {
            proxy_pass http://driveup-prod-backend:4100;
        }
    }
}