events {}

http {
    server {
        listen 80;

        location /api {
            proxy_pass http://backend:4100;
        }

        location /visualizer {
            proxy_pass http://visualizer:8080;
        }
    }
}