events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://driveup-staging-frontend:5173;
        }

        location /api {
            proxy_pass http://driveup-staging-backend:4100;
        }

        location /visualizer {
            proxy_pass http://driveup-staging-visualizer:8080;
        }
    }
}