events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://driveup-staging-client:5173;
        }

        location /api {
            proxy_pass http://driveup-staging-server:4100;
        }
    }
}