name: Compile and push images to Yann DockerHub

# Controls when the workflow will run

on:
  push:
    branches: ["dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add services here
        service:
          - client
          - server

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v1
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DRIVEUP_ACCESS_TOKEN }}

      # prepare buildx for docker

      - uses: docker/setup-buildx-action@v1
        name: Set up Docker Buildx

      # build and push the newly created image

      - uses: docker/build-push-action@v2
        name: Build and push
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/driveupstaging${{ matrix.service }}:latest


    notify-server:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Notify server
          run: |
            curl -X POST http://51.68.58.81:9000/hooks/update-staging-driveup