name: e2e-test-workflow

on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

jobs:
  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installer Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set environment variables
        run: |
           echo "DB_PASSWORD=${{ secrets.DB_PASSWORD_TEST }}" >> $GITHUB_ENV
           echo "DB_SCHEMA=${{ secrets.DB_SCHEMA_TEST }}" >> $GITHUB_ENV
           echo "DB_USER=${{ secrets.DB_USER_TEST }}" >> $GITHUB_ENV
           echo "DB_HOST=${{ secrets.DB_HOST_TEST }}" >> $GITHUB_ENV
           echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV
           echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
           echo "GATEWAY_PORT=7100" >> $GITHUB_ENV
           echo "SERVER_HOST=${{ secrets.SERVER_HOST }}" >> $GITHUB_ENV
           echo "CLIENT_HOST=${{ secrets.CLIENT_HOST }}" >> $GITHUB_ENV
           echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
           echo "USER_PASSWORD=${{ secrets.USER_PASSWORD }}" >> $GITHUB_ENV

      - name: Build and run Docker Compose
        run: |
          docker-compose -f compose.e2e.yaml up -d --build

      - name: Seed the database
        run: |
          docker exec driveup-test-server npm run seed:test

      - name: Run E2E tests
        run: |
          cd e2e
          npm install
          npm run test
      
      - name: Install Playwright Browsers
        run: |
          cd e2e
          npx playwright install --with-deps

      - name: Stop and clean up Docker containers
        if: always()
        run: |
          docker-compose -f compose.e2e.yaml down
